# Generated by Django 3.1.4 on 2020-12-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_carrera_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre carrera')),
                ('code', models.CharField(choices=[('IINF', 'IINF'), ('IGEM', 'IGEM'), ('ISIC', 'ISIC'), ('IMCT', 'IMCT'), ('IIND', 'IIND'), ('IIAL', 'IIAL')], default='INGF', max_length=5)),
            ],
            options={
                'verbose_name': 'Carreras',
            },
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
    ]
