# Generated by Django 3.1.4 on 2020-12-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20201214_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre organización')),
                ('entidad', models.CharField(max_length=100, verbose_name='Entidad')),
                ('localidad', models.CharField(max_length=100, verbose_name='Localidad')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('domicilio', models.CharField(max_length=100, verbose_name='Domicilio')),
                ('cp', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('email', models.CharField(max_length=100, verbose_name='Correo electronico')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
    ]
