# Generated by Django 3.1.4 on 2020-12-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20201214_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Contacto')),
                ('parents', models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hermano', 'Hermano'), ('Hermana', 'Hermana'), ('Tio', 'Tio'), ('Tia', 'Tia'), ('Abuelo', 'Abuelo'), ('Abuela', 'Abuela'), ('Otro', 'Otro')], default='Madre', max_length=20, verbose_name='Parentesco')),
                ('entidad', models.CharField(max_length=100, verbose_name='Entidad')),
                ('localidad', models.CharField(max_length=100, verbose_name='Localidad')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('domicilio', models.CharField(max_length=100, verbose_name='Domicilio')),
                ('cp', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('email', models.CharField(max_length=100, verbose_name='Correo electronico')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
