# Generated by Django 3.1.4 on 2020-12-14 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huella', models.CharField(max_length=10, unique=True, verbose_name='Identificación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.career', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
    ]
