# Generated by Django 3.1.4 on 2020-12-14 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, verbose_name='Clave')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del proyecto')),
                ('status', models.DurationField(verbose_name='Estado del proyecto')),
                ('qualification', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Calificación')),
                ('period', models.CharField(max_length=50, verbose_name='Periodo')),
                ('Organizations_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.organizations', verbose_name='Organización')),
                ('Students_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.students', verbose_name='Alumno')),
                ('Teachers_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.teachers', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Residencia',
                'verbose_name_plural': 'Residencias',
            },
        ),
    ]
